// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=cellar/design
// --out=$(GOPATH)/src/cellar
// --version=v1.1.0-dirty
//
// API "cellar": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package client
